### ISSUE TITLE
结果复现疑问

### ISSUE THREAD

**Issue by CreaterLL** [easezyc/WSDM2022-PTUPCDR#2]
您好，读了您的文章，感觉很有启发，但我还是有一些疑问：
①关于冷启动与热启动。原文说的是数据划分成1:1，具体怎么划分这里并不是很理解，也没有找到相关代码，似乎项目中是直接全部用来测试冷启动的（可能是我没看懂）？
②关于文中table-2冷启动测试结果，请问是基于MF、GMF还是YouTube DNN的呢？
③关于热启动部分，微调和相关测试代码都没有找到，请问方便共享一下吗？

**Comment by easezyc** [comment]
1. 首先将用户根据比例20%，50%，80%划分训练用户和测试用户。得到测试用户集合后，针对纯冷启动场景，测试用户的所有数据都拿来测试（这里论文里可能写的有点误导了）。针对热启动场景，把这些用户的所有交互根据根据时间1:1划分，第一份用于测试冷启动的效果，第二份用于测试热启动的效果（在第一份数据微调之后），对于文中图4的浅色和深色的柱子。热启动的代码是额外写的，开源的代码这里没有，有需要你可以按照这个逻辑去实现。
2. 除了图4，所有结果都是基于MF的。
3. 这个工作用的那个服务器的硬盘坏了，所以代码和数据都没了，我这里开源的代码是之前提交论文时附的代码（不然这份代码也没了），所以我这里也没给到大家我当时划分好的数据集，只能自己重新去划分。热启动你按照我说的那个流程去复现就好了，做起来很简单。

**Comment by easezyc** [comment]
说错了，除了图3都是基于MF

**Comment by CreaterLL** [comment]
你好，table-2中的结果都是默认超参数吗（如10个epoch），还是有改动呢？

**Comment by easezyc** [comment]
是的，都是按照代码里的10个epoch跑的

**Comment by saladcat** [comment]
> 是的，都是按照代码里的10个epoch跑的

无法复现paper里的结果，
在task1中，代码跑出来比paper报告的要好，
在task3中，代码跑出来比paper报告的要差
这很奇怪，请问参数没有变化吗？或者是数据的问题？
```
task 3 --ratio [0.8,0.2]
{'tgt_mae': 4.4912872314453125, 'tgt_rmse': 5.175125598907471, 'aug_mae': 1.7872928380966187, 'aug_rmse': 2.34104585647583, 'emcdr_mae': 1.6219780445098877, 'emcdr_rmse': 1.921657919883728, 'ptupcdr_mae': 1.2009096145629883, 'ptupcdr_rmse': 1.5727365016937256}
```


```
task 3 --ratio [0.2,0.8]
{'tgt_mae': 4.5320940017700195, 'tgt_rmse': 5.223546028137207, 'aug_mae': 2.6682167053222656, 'aug_rmse': 3.3993022441864014, 'emcdr_mae': 2.600187063217163, 'emcdr_rmse': 2.926187753677368, 'ptupcdr_mae': 1.7992867231369019, 'ptupcdr_rmse': 2.453801155090332}
```

**Comment by easezyc** [comment]
我在别的issue里已经提到这个了，这里公开的代码是附着paper一起提交的代码，没有我划分的原始数据，原始数据在老的服务器上，那个服务器硬盘坏了，数据搞不出来。重新下载数据再用我提供的划分数据的文件划分，划分出来的数据肯定是不同的（随机种子、机器差异等问题导致），结果自然不同，你跑的结果依然能证明ptupcdr显著好于这些baseline即可。

**Comment by saladcat** [comment]
> 我在别的issue里已经提到这个了，这里公开的代码是附着paper一起提交的代码，没有我划分的原始数据，原始数据在老的服务器上，那个服务器硬盘坏了，数据搞不出来。重新下载数据再用我提供的划分数据的文件划分，划分出来的数据肯定是不同的（随机种子、机器差异等问题导致），结果自然不同，你跑的结果依然能证明ptupcdr显著好于这些baseline即可。

Get，只是和原文的绝对值差太多了所以有疑问，感谢

**Comment by easezyc** [comment]
> > 我在别的issue里已经提到这个了，这里公开的代码是附着paper一起提交的代码，没有我划分的原始数据，原始数据在老的服务器上，那个服务器硬盘坏了，数据搞不出来。重新下载数据再用我提供的划分数据的文件划分，划分出来的数据肯定是不同的（随机种子、机器差异等问题导致），结果自然不同，你跑的结果依然能证明ptupcdr显著好于这些baseline即可。
> 
> Get，只是和原文的绝对值差太多了所以有疑问，感谢

可以考虑重新划分，你这个划分可能对overlapping的数据量很敏感。@saladcat

**Comment by saladcat** [comment]
好的，我试试看，谢谢！

**Comment by pureb1ack1** [comment]
作者大大，我想尝试看懂您的代码，请问train_meta数据是指的是什么呀

**Comment by easezyc** [comment]
> 好的，我试试看，谢谢！

我找到我们跑实验用的数据了，你可以基于我上传的这份数据跑。

**Comment by easezyc** [comment]
> 作者大大，我想尝试看懂您的代码，请问train_meta数据是指的是什么呀

PTUPCDR使用的训练数据，具体参见代码。

**Comment by LiuerH** [comment]
作者大大，您的实验结果写的运行五次取平均值，这五次全都是从生成数据开始吗？还是固定生成数据不动跑五次run取平均值呢

**Comment by easezyc** [comment]
@LiuerH 固定生成数据，跑五次不同的种子取均值
