### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by diyicheng** [easezyc/WSDM2022-PTUPCDR#5]
why pytorch and tensorflow use in a package?  when i run the code, ModuleNotFoundError: No module named 'tensorflow'

**Comment by easezyc** [comment]
It is convinient to use keras to process squence. If you have better way to achieve this operation, you could replace the following code.
pos_seq = keras.preprocessing.sequence.pad_sequences(data.pos_seq.map(self.seq_extractor), maxlen=20, padding='post')

**Comment by diyicheng** [comment]
thank you，i have solve the problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yongchun ***@***.***&gt;; 
发送时间: 2022年11月4日(星期五) 晚上8:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easezyc/WSDM2022-PTUPCDR] a question (Issue #5)





 
It is convinient to use keras to process squence. If you have better way to achieve this operation, you could replace the following code.
 pos_seq = keras.preprocessing.sequence.pad_sequences(data.pos_seq.map(self.seq_extractor), maxlen=20, padding='post')
